defaultPlatforms:
  - linux/amd64
  - linux/arm64

builds:
  - id: pacani-bot
    main: ./main.go
    flags:
    - -tags
    - netgo
    - -trimpath
    ldflags:
    - -s -w
    - -extldflags "-static"